Disable vm health check.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -12,30 +12,30 @@ jobs:
           name: "Start Ray container"
           command: |
             docker run -d --name ray -p 8265:8265 -v /tmp:/tmp rayproject/ray:2.45.0-py312-cpu ray start --head --disable-usage-stats --block --dashboard-host 0.0.0.0
-      - run:
-          name: "Wait for Ray cluster to be accessible from host machine"
-          command: |
-            echo "Checking if Ray cluster is accessible from host machine..."
-            max_retries=30
-            counter=0
-            while [ $counter -lt $max_retries ]; do
-              # Run wget with strict timeout and only one try
-              wget -q --timeout=3 --tries=1 --dns-timeout=3 --connect-timeout=3 --read-timeout=3 http://127.0.0.1:8265
-              if [ $? -eq 0 ]; then
-                # Success
-                break
-              fi
-              
-              counter=$((counter + 1))
-              if [ $counter -eq $max_retries ]; then
-                echo "Ray cluster failed to be accessible after $max_retries attempts."
-                docker logs ray
-                exit 1
-              fi
-              echo "Ray cluster not accessible yet. Waiting (attempt $counter/$max_retries)..."
-              sleep 2
-            done
-            echo "Ray cluster is accessible from host machine!"
+      # - run:
+      #     name: "Wait for Ray cluster to be accessible from host machine"
+      #     command: |
+      #       echo "Checking if Ray cluster is accessible from host machine..."
+      #       max_retries=30
+      #       counter=0
+      #       while [ $counter -lt $max_retries ]; do
+      #         # Run wget with strict timeout and only one try
+      #         wget -q --timeout=3 --tries=1 --dns-timeout=3 --connect-timeout=3 --read-timeout=3 http://127.0.0.1:8265
+      #         if [ $? -eq 0 ]; then
+      #           # Success
+      #           break
+      #         fi
+
+      #         counter=$((counter + 1))
+      #         if [ $counter -eq $max_retries ]; then
+      #           echo "Ray cluster failed to be accessible after $max_retries attempts."
+      #           docker logs ray
+      #           exit 1
+      #         fi
+      #         echo "Ray cluster not accessible yet. Waiting (attempt $counter/$max_retries)..."
+      #         sleep 2
+      #       done
+      #       echo "Ray cluster is accessible from host machine!"
       - run:
           name: "Wait for Ray cluster to be healthy inside container"
           command: |
